{{- if .Values.letsencrypt.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: {{ .Values.letsencrypt.email }}
    server: {{ .Values.letsencrypt.server }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.className }}
            ingressTemplate:
              metadata:
                {{- with .Values.letsencrypt.annotations }}
                annotations:
                  {{- toYaml . | nindent 18 }}
                {{- end }}
{{- end }}
