{{- if .Values.secretEnv }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "eks-demo-app.fullname" . }}
type: Opaque
data:
  {{- range .Values.secretEnv }}
  {{ .name }}: {{ .value | b64enc }}
  {{- end }}
{{- end }}
