{{- if .Values.awsSecretsManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "eks-demo-app.name" . -}}-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: {{ .Values.awsSecretsManager.awsSecretName }}
          objectType: "secretsmanager"
{{- end }}
