name: build

on: 
  pull_request:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.9.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./demo/requirements.txt -r ./demo/requirements_dev.txt
      - name: Lint with pylint
        run: |
          pylint --errors-only ./demo
      - name: Test with pytest
        run: |
          pytest -v --cov=demo --cov-report=xml:coverage.xml
      - name: Upload coverage report to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
